agent-token-secret: my-kubernetes-secret
buildkite-token: abcdef
debug: true
image: my.registry.dev/buildkite-agent:latest
job-ttl: 5m
max-in-flight: 100
namespace: my-buildkite-ns
org: my-buildkite-org
# only set if the pipelines are in a cluster
# the UUID may be found in the cluster settings
cluster-uuid: beefcafe-abbe-baba-abba-deedcedecade
tags:
  - queue=my-queue
  - priority=high
pod-spec-patch:
  serviceAccountName: 'buildkite-agent-sa'
  automountServiceAccountToken: true
  containers:
    - name: container-0
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-secrets
              key: github-token
