agent-token-secret: my-kubernetes-secret
buildkite-token: abcdef
debug: true
image: my.registry.dev/buildkite-agent:latest
job-ttl: 5m
max-in-flight: 100
namespace: my-buildkite-ns
org: my-buildkite-org
# only set if the pipelines are in a cluster
# the UUID may be found in the cluster settings
cluster-uuid: beefcafe-abbe-baba-abba-deedcedecade
tags:
  - queue=my-queue
  - priority=high
# ssh-credentials-secret are the secret with the ssh credentials
# configured on the agent with docker-ssh-config
# @see https://github.com/buildkite/docker-ssh-env-config
ssh-credentials-secret: buildkite-ssh-github-creds
